### ISSUE TITLE
variable $default-layout-direction not changing direction

### ISSUE THREAD

**Issue by ahwebd** [thoughtbot/neat#387] opened 2015-10-27 08:49 UTC
variable $default-layout-direction not changing direction.

In file "neat/grid/_private.scss" line 6, changing:
```css
$layout-direction: LTR !default;
```
to
```css
$layout-direction: $default-layout-direction !global;
```
fixed the issue

**Comment by whmii** [comment] 2016-07-06 19:58
I'm not sure what the issue is here. Closing for now, feel free to reopen.

**Closed by whmii** 2016-07-06 19:58 UTC
