### ISSUE TITLE
Grid issues

### ISSUE THREAD

**Issue by kresogalic8** [thoughtbot/neat#450] opened 2016-07-01 08:15 UTC
Hello guys, i have some problems with grid system. Maybe i am doing something wrong but this is what it is. I am trying to have different columns at different screens.

For example: 

```
.project {
        @include span-columns(3);
        @include omega(4n);
        @include media(min-width 1280px) {
            @include span-columns(4);
            @include omega(3n);
        }
}
```

Ok, so the problem here is that i am getting margin-right: 0 for 4th element, but i want only 3th element to remove that margin after 1200px width. What is wrong? 

Thanks in advance

**Comment by danbee** [comment] 2016-07-01 13:46
@kresogalic8 The problem here is that the `omega(4n)` mixin is getting applied all the time, then you're adding the `omega(3n)` mixin on top. This means you're getting `margin-right: 0` applied to every 3rd *and* every 4th element when the viewport is 1280px+ wide.

You need to put the `omega(4n)` in a media query as well so it only gets applied when the viewport is narrower than 1280px. You could put the `span-columns` in there as well.

```sass
.project {
  @include media(max-width 1279px) {
    @include span-columns(3);
    @include omega(4n);
  }
  @include media(min-width 1280px) {
    @include span-columns(4);
    @include omega(3n);
  }
}
```

**Comment by kresogalic8** [comment] 2016-07-01 13:55
Hm i think u didnt understand.

By default in class i added span-columns(6) and omega(2n) - so 2.4.6.8 and so on will have margin-right: 0...

After that i added span-columns(4) and omega(3n) in min-width 1280px and up - and then what is the issues is that 2.4.6.8 and 3.6.9 and so on will get margin-right: 0...

Here are the screenshots

Default
<img width="935" alt="screen shot 2016-07-01 at 3 54 07 pm" src="https://cloud.githubusercontent.com/assets/7289406/16523513/23746a28-3fa4-11e6-8e39-dd9cd80f0c67.png">

1280 and wider
<img width="1150" alt="screen shot 2016-07-01 at 3 54 18 pm" src="https://cloud.githubusercontent.com/assets/7289406/16523512/2372a242-3fa4-11e6-9df3-9b38571e1149.png">

**Comment by danbee** [comment] 2016-07-01 14:30
Hi @kresogalic8, I did understand. The problem is that the code you wrote will apply both `omega` mixins at 1280px and above, hence why you get `margin-right: 0` at 2-4-6-8 **and** at 3-6-9. You need to put the first `omega` mixin in a media query to avoid this happening.

Here is the code you'll want for your use case. Note that the first media query is only applied below 1280px.

```sass
.project {
  @include media(max-width 1279px) {
    @include span-columns(6);
    @include omega(2n);
  }
  @include media(min-width 1280px) {
    @include span-columns(4);
    @include omega(3n);
  }
}
```

**Comment by whmii** [comment] 2016-07-06 18:27
@kresogalic8

@danbee's fix should work. I'm closing this for now but feel free to reopen if you're still encountering issues.

**Closed by whmii** 2016-07-06 18:27 UTC
