### ISSUE TITLE
Neat fails on import using DartSass 1.11.0 and 1.12.0

### ISSUE THREAD

**Issue by RazorfieldSquirrel** [thoughtbot/neat#654] opened 2018-08-16 18:08 UTC
Neat 3.0 fails on import using DartSass 1.11 and 1.12 

1. Install dart sass (MacOS 10.13.6) via `brew install sass/sass/sass`
2. install neat via ruby gem `gem install neat`
3. Install neat to the working directory `neat install`
4. Create SASS file -- ie main.scss
5. Import Bourbon and Neat via `@import "bourbon/bourbon";
@import "neat/neat";`
6. Compile via CLI `sass main.scss main.css`
7. Error `Error: expected "(".<br />
  } @else if length($span) == 2 or if length($span) >= 3 {
                                     ^
  neat/neat/functions/_neat-parse-columns.scss 19:38  root stylesheet
  neat/_neat.scss 16:9                                @import
  main.scss 4:9                                       root stylesheet`

I assume this is because Neat has a dependency on RubySass that isn't present in DartSass but since Ruby is being deprecated and both bourbon and bitters work fine it seems like an oversight unless I'm making a mistake (always possible!)

- Neat Version: 3.0.0
- Build Tool or Environment: DartSass 1.11/1.12.0
- Browser/OS: Mac OS 10.13.6

**Comment by imdan** [comment] 2018-08-25 01:15
Yeah I'm having this same issue after updating to macos 10.13.6.

**Comment by bizMD** [comment] 2018-08-30 10:51
I'm running into the same issue, but I resolved it by replacing that line with this:

```
} @else if length($span) == 2 or if(length($span) >= 3) {
```

It's not a Ruby dependency, but a syntax issue. I'm not sure if the issue is with Neat or with the npm implementation of Sass, but this workaround seems to do the trick.

**Comment by bizMD** [comment] 2018-09-06 10:39
I've closed my PR after a week of not getting accepted. Hopefully another person will be able to fix the issue. :)

**Comment by whmii** [comment] 2018-11-09 15:37
@bizMD I believe this issue has been resolved in master. Pending a few other PRs a release should be issued this week. Closing for now but if the issue persists feel free to re-open.

**Closed by whmii** 2018-11-09 15:37 UTC
