### ISSUE TITLE
Few Questions...

### ISSUE THREAD

**Issue by Log1x** [thoughtbot/neat#548] opened 2017-02-23 03:32 UTC
Hi.

Sorry for putting this on the issue tracker, but as there is not a forum dedicated to Bourbon projects, this seemed like the only place.

I was just curious why Neat 2.0 opts to `margin-left: $gutter` the first child of a container that contains multiple columns? It tends to make things not perfectly center. Perhaps I'm just doing it wrong,

Also curious if you could elaborate on the examples a little bit? Coming from Neat 1.8.1 was a little rough.

It looks like Neat is going for a mobile-first approach judging by `grid-media` using `min-width` instead of `max-width` for it's `media` setting value. For the time being, I just did something along the lines of:

```
// Grid
$width:   1200px !default;
$gutter:  20px   !default;
$columns: 12     !default;

// Screen Sizes
$large: (
  media: "only screen and (max-width: 992px)",
  gutter: 0,
) !default;

$medium: (
  media: "only screen and (max-width: 768px)",
  gutter: 0,
) !default;

$small: (
  media: "only screen and (max-width: 480px)",
  gutter: 0,
) !default;

// Collapse
$collapse: (
  gutter: 0,
) !default;
```

until I am more acquainted with 2.0.

Curious what configurations people are going with for complex sites now? Is Neat going more towards a Flexbox approach?

Right now I just opted to make a `container` mixin that is similar to how `outer-container` used to work.

**Example**

```
@mixin container {
  @include grid-container;
  margin-left: auto;
  margin-right: auto;
  max-width: $width;
  padding: 0 15px;
}
```

But I feel like that is not the intended usage with the new approach of 2.0, so I'd like to know where I should start in updating my way of doing things.

I'd mainly just like pointers and possible examples on how to do the above in a more efficient way that uses the methodology 2.0 was developed for.

Thanks in advance.

**Comment by kgcreative** [comment] 2017-02-23 03:42
Just a few things:

`$gutter` is the spacing between columns, not the outer gutter of a container.

If you want a grid container that consumes its gutter so it's flush with the content, you want to add `grid-collapse`.

The way neat calculates columns, is that it accounts only for margin left, and the gap for margin right is what centers. Layout. Once you grok the system, then you see that a 12 com object centers itself within the grid container.

I'll try and get a better answer once I'm not typing this on a tiny keyboard, but this should help some.

**Comment by Log1x** [comment] 2017-02-23 03:47
> $gutter is the spacing between columns, not the outer gutter of a container.
>
> If you want a grid container that consumes its gutter so it's flush with the content, you want to add grid-collapse.

Gotcha. That makes sense. Still unsure about my other methods though and how I can do things more efficiently. Thanks in advance for your extended answer. :)

**Comment by kgcreative** [comment] 2017-02-23 03:59
For custom grids, I went the opposite direction. I defined a set of variables that determine my boundaries, then created a group of custom grids that could, conditionally, pretty much cover any need i have. Some items I want to call using max width only, some min width only, others yet I want to constrain to a single breakpoint. This gives me a lot of flexibility when, for example, I want a group of cards to reflow from 5 per row to 3, to 2, and finally to single column on mobile. By setting up my boundaries this way I can call them in a variety of settings and needs

Notice that in my lg and xl breakpoints my gutters go from 20px to 30px

```
// -----------------------------------------------------------------------------
// 1. Breakpoints
// -----------------------------------------------------------------------------
//
/// Breakpoint Boundaries
/// @type length
// These correspond to the Bootstrap 4 Responsive Breakpoints
// Lower boundaries
$screen-xs-min:               0px !default;
$screen-sm-min:               576px !default;
$screen-md-min:               768px !default;
$screen-lg-min:               1024px !default;
$screen-xl-min:               $max-width !default;
// Upper boundaries
$screen-xs-max:               $screen-sm-min - 1px !default;
$screen-sm-max:               $screen-md-min - 1px !default;
$screen-md-max:               $screen-lg-min - 1px !default;
$screen-lg-max:               $screen-xl-min - 1px !default;
// Custom neat grids:
// XS
$media-xs-only: (
    columns: 6,
    media: 'only screen and (max-width: #{$screen-xs-max})',
);
// SM
$media-sm: (
    columns: 12,
    media: $screen-sm-min,
);
$media-sm-only: (
    columns: 12,
    media: 'only screen and (min-width: #{$screen-sm-min}) and (max-width: #{$screen-sm-max})',
);
$media-sm-max: (
    columns: 12,
    media: 'only screen and (max-width: #{$screen-sm-max})',
);
// MD
$media-md: (
    columns: 12,
    media: $screen-md-min,
);
$media-md-only: (
    columns: 12,
    media: 'only screen and (min-width: #{$screen-md-min}) and (max-width: #{$screen-md-max})',
);
$media-md-max: (
    columns: 12,
    media: 'only screen and (max-width: #{$screen-md-max})',
);
// LG
$media-lg: (
    columns: 12,
    gutter: 30px,
    media: $screen-lg-min,
);
$media-lg-only: (
    columns: 12,
    gutter: 30px,
    media: 'only screen and (min-width: #{$screen-lg-min}) and (max-width: #{$screen-lg-max})',
);
$media-lg-max: (
    columns: 12,
    gutter: 30px,
    media: 'only screen and (max-width: #{$screen-lg-max})',
);
// XL
$media-xl: (
    columns: 12,
    gutter: 30px,
    media: $screen-xl-min,
);
$media-print: (
    columns: 12,
    gutter: .25in,
    media: 'only print',
);
```

**Comment by Log1x** [comment] 2017-02-23 04:05
Ahh. Good! 

I wasn't as crazy as I thought I was being for using `max-width` instead of the default implementation of `min-width` seen in [_neat-parse-media.scss](https://github.com/thoughtbot/neat/blob/master/core/neat/functions/_neat-parse-media.scss).

So is my example `container` mixin still deemed sane then? Is there anything I could be doing better or am I just overthinking it?

Thanks!

**Comment by kgcreative** [comment] 2017-02-23 04:24
Grid media was designed to either use a number value as min width, or use a string otherwise, that way you can pass it complex media queries.

I would really encourage you to use both min and max if you're not going to stack properties in a mobile-first approach, since neat by default inherits your grid settings ahead of any custom properties.

I would sepparate your grid objects from your container Mixin. I.e. Only emit a grid object if you need to add columns to a section of your layout. That will allow for proper centering of your layouts. So:

```
<!-- HTML: -->
<article> <!-- apply your container Mixin here -->
 <section>
    <div class="card">
       Card content
    </div>
    <div class="card">
       Card content
    </div>
    <div class="card">
       Card content
    </div>
  <section>
</article>
```

```
// scss

article {
  margin-left: auto;
  margin-right: auto;
  width: 100%;
  max-width: 1200px;
  padding: $gutter;
}

section {
@include grid-container;
@include grid-collapse;
}

.card {
@include grid-column(1 of 3);
}
```

Plus whatever responsive behavior you need

**Comment by whmii** [comment] 2017-02-23 21:42
yep, looks good.

**Comment by whmii** [comment] 2017-03-02 02:34
@Log1x seems like things got sorted so I'm going to close this but feel free to re-open if you need any further clarification.

**Closed by whmii** 2017-03-02 02:34 UTC
